networks:
  services:
    external: true

services:
    rundeck:
        container_name: rundeck
        build:
          context: rundeck
          args:
            RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:3.3.10}
        links:
          - mysql
        environment:
            RUNDECK_GRAILS_URL: https://rundeck.refrain.work
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.rundeck.rule=Host(`rundeck.refrain.work`)"
          - "traefik.http.routers.rundeck.entrypoints=https"
          - "traefik.http.routers.rundeck.tls=true"
          - "traefik.http.services.rundeck.loadbalancer.server.port=4440"
        networks:
          - services
        security_opt:
          - no-new-privileges:true
    mysql:
        container_name: mysql
        image: mysql:8
        expose:
          - 3306
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE reduces error messages in console
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
        networks:
          - services
    client:
      container_name: client
      build:
        context: client
        args:
          BUILD_DEV_IMAGE: ${BUILD_DEV_IMAGE:-rundeckpro/env-builder:latest}
      environment:
        CONFIG_FILE: /app/data/import.yml
        CONFIG_FILES_PATH: /app/data
        RUNDECK_URL: http://rundeck:4440
        RUNDECK_API_URL: http://rundeck:4440
        RUNDECK_USER: ${RUNDECK_USER:-admin}
        RUNDECK_PASSWORD: ${RUNDECK_PASSWORD:-admin}
        # generate key for nodes
        KEY_PATH: /app/data/keys
      volumes:
        - shared-volume:/app/data/keys/
      networks:
        - services
    node:
      container_name: node1
      build:
        context: node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
        - KEY_PATH=/app/data
      volumes:
        - shared-volume:/app/data/
      networks:
        - services

volumes:
  shared-volume:
